---
- hosts: testsrvs
  gather_facts: no
  remote_user: root
  vars_files: 
     - users.yml
  tasks:
  - name: Create groups
    group: name={{ item.key }} state=present
    with_dict: "{{ grupos }}"
  - name: Add groups perms into sudoers
    lineinfile: dest=/etc/sudoers state=present line='%{{ item.key }} ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
    with_dict: "{{ grupos }}"
  - name: Create Users
    user: name={{ item.value.name }} comment="{{ item.value.comment }}" group={{ item.value.group }}
    with_dict: "{{ users }}"
  - name: Put a simple password
    shell: 'echo {{ item.value.name }} | passwd {{ item.value.name }} --stdin'
    with_dict: "{{ users }}" 
  
